# Generated by Django 2.2.5 on 2019-09-25 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category1',
        ),
        migrations.AddField(
            model_name='site',
            name='area_hectares',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='description',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='justification',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('states1', models.CharField(max_length=128)),
                ('category1', models.ManyToManyField(through='unesco.Site', to='unesco.Category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='states2',
            field=models.ManyToManyField(through='unesco.Site', to='unesco.States'),
        ),
        migrations.AddField(
            model_name='site',
            name='states',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='unesco.States'),
            preserve_default=False,
        ),
    ]
