# Generated by Django 2.2.5 on 2019-09-25 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0002_auto_20190925_0419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso1', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region1', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='states2',
        ),
        migrations.RemoveField(
            model_name='states',
            name='category1',
        ),
        migrations.AddField(
            model_name='site',
            name='iso',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='unesco.Iso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='region',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='unesco.Region'),
            preserve_default=False,
        ),
    ]
